[package]
name = "massren"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3.2.7", features = ["derive"] }
serde = "1.0"
serde_derive = "1.0"
serde_yaml = "0.8"
colored = "2.0"