[package]
name = "massren"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3.2", features = ["derive"] }
colored = "2.0"
glob = "0.3"
tempfile = "3.3"
dialoguer = "0.10"
